program: sweep.py
method: bayes
project: TDT17-mini-project
entity: jofalck-ntnu
metric: 
  name: metrics/mAP50-95(B)
  goal: maximize
parameters:
  batch:
    distribution: categorical
    values:
      - 16
  conf:
    distribution: uniform
    max: 0.5
    min: 0.2
  hsv_h:
    distribution: uniform
    max: 0.04
    min: 0.01
  hsv_s:
    distribution: uniform
    max: 0.9
    min: 0.5
  hsv_v:
    distribution: uniform
    max: 1
    min: 0.2
  imgsz:
    distribution: categorical
    values: [1344, 1440, 1536, 1920]
  lr0:
    distribution: uniform
    max: 0.1
    min: 0.005
  momentum:
    distribution: uniform
    max: 0.8
    min: 0.35
  optimizer:
    distribution: categorical
    values:
      - SGD